package fr.insa.recettes.controleur;

public enum TypeOrdre {
    SHOW_ACCUEIL,
    SHOW_INVENTAIRE,
    SHOW_CREATION_RECETTE,
    SHOW_LISTE_RECETTES,
    INGREDIENT_AJOUTE,
    INGREDIENT_MODIFIE,
    INGREDIENT_SUPPRIME,
    RECETTE_AJOUTEE,
    ERREUR_INGREDIENT_EXISTANT,
    ERREUR_INGREDIENT_INTROUVABLE,
    ERREUR_RECETTE_EXISTANTE,
    ERREUR_RECETTE_INTROUVABLE,
    DATA_LOAD,
    RECETTE_MODIFIEE,
    RECETTE_SUPPRIMEE
}